# -*- coding: utf-8 -*-
"""
Django settings for alldev project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from .base import *

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    # postgresql setting
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        # 'HOST': '',  # NAS 배포용
        # 'PORT': '',
        'HOST': '',  # LOCAL 개발용
        'PORT': '',
    },
    # mongodb setting
    # 'default': {
    #     'ENGINE': 'djongo',  # https://nesdis.github.io/djongo/
    #     'NAME': '',
    #     'USERNAME': '',
    #     'PASSWORD': '',
    #     'CLIENT': {'host': ''},  # LOCAL 개발용
    #     'PORT': 27017,
    # },
}

# celery Setting
# Other Django configurations...
# Celery application definition
# http://docs.celeryproject.org/en/v4.2.1/userguide/configuration.html
MONGODB_URL = 'mongodb://{USER}:{PASSWORD}@{IP}/{DBNAME}'

CELERY_BROKER_URL = MONGODB_URL
CELERY_RESULT_BACKEND = MONGODB_URL
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul'
# CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = False
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
