# Generated by Django 3.1.1 on 2020-10-15 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCd',
            fields=[
                ('cd', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockStrategyBaseCd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=6, unique=True)),
                ('level', models.SmallIntegerField()),
                ('required', models.BooleanField(null=True)),
                ('comment', models.TextField()),
                ('prnt_cmd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namuh_bot.stockstrategybasecd', to_field='cmd')),
            ],
        ),
        migrations.CreateModel(
            name='StockStrategyParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('base_cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namuh_bot.stockstrategybasecd')),
            ],
        ),
    ]
