# Generated by Django 2.1.2 on 2018-11-28 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinCode', models.CharField(max_length=7)),
                ('openingPrice', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('closingPrice', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('minPrice', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('maxPrice', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('averagePrice', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('unitsTraded', models.FloatField(default=0.0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('volume1Day', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('volume7Day', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('buyPrice', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('sellPrice', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('dayFluctate', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('dayFluctate_rate', models.FloatField(default=0.0, validators=[django.core.validators.RegexValidator('^[0-9]+\\.?[0-9]+$')])),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
